//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gumruk.DayaLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Gumruk.Entity;
    public partial class GumrukDBContext : DbContext
    {
        public GumrukDBContext()
            : base("name=GumrukDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<app_module_procedures> app_module_procedures { get; set; }
        public virtual DbSet<customs_articles> customs_articles { get; set; }
        public virtual DbSet<customs_circulars> customs_circulars { get; set; }
        public virtual DbSet<customs_codes> customs_codes { get; set; }
        public virtual DbSet<d_b_column_types> d_b_column_types { get; set; }
        public virtual DbSet<d_b_schema_procedures> d_b_schema_procedures { get; set; }
        public virtual DbSet<d_b_schemas> d_b_schemas { get; set; }
        public virtual DbSet<d_b_tables> d_b_tables { get; set; }
        public virtual DbSet<migrations> migrations { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<password_resets> password_resets { get; set; }
        public virtual DbSet<d_b_columns> d_b_columns { get; set; }
        public virtual DbSet<d_b_column_lookups> d_b_column_lookups { get; set; }
        public virtual DbSet<d_b_table_explanation> d_b_table_explanation { get; set; }
        public virtual DbSet<d_b_column_explanations> d_b_column_explanations { get; set; }
        public virtual DbSet<app_base_modules> app_base_modules { get; set; }
        public virtual DbSet<app_module_operations> app_module_operations { get; set; }
        public virtual DbSet<app_sub_modules> app_sub_modules { get; set; }
        public virtual DbSet<d_b_column_links> d_b_column_links { get; set; }
        public virtual DbSet<ERxml> ERxml { get; set; }
        public virtual DbSet<GumrukIdareleri> GumrukIdareleri { get; set; }
        public virtual DbSet<KimlikTurleri> KimlikTurleri { get; set; }
        public virtual DbSet<Limanlar> Limanlar { get; set; }
        public virtual DbSet<OzelTuzelSahis> OzelTuzelSahis { get; set; }
        public virtual DbSet<OzetBeyan> OzetBeyan { get; set; }
        public virtual DbSet<TasimaSekilleri> TasimaSekilleri { get; set; }
        public virtual DbSet<TasitBilgileri> TasitBilgileri { get; set; }
        public virtual DbSet<Ulkeler> Ulkeler { get; set; }
        public virtual DbSet<BeyanTurleri> BeyanTurleri { get; set; }
        public virtual DbSet<DBErrorMessages> DBErrorMessages { get; set; }
        public virtual DbSet<SQLProcedures> SQLProcedures { get; set; }
        public virtual DbSet<SQLKeys> SQLKeys { get; set; }
        public virtual DbSet<SQLProceduresComments> SQLProceduresComments { get; set; }
        public virtual DbSet<SQLProceduresProcedure> SQLProceduresProcedure { get; set; }
        public virtual DbSet<Modules> Modules { get; set; }
        public virtual DbSet<ModulesFiles> ModulesFiles { get; set; }
        public virtual DbSet<SubModules> SubModules { get; set; }
        public virtual DbSet<SQLProcedureModules> SQLProcedureModules { get; set; }
        public virtual DbSet<ModulesTables> ModulesTables { get; set; }
        public virtual DbSet<ObjType> ObjType { get; set; }
        public virtual DbSet<DBObjects> DBObjects { get; set; }
        public virtual DbSet<DBObjectsChilds> DBObjectsChilds { get; set; }
        public virtual DbSet<InnerModule> InnerModule { get; set; }
    }
}
