//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gumruk.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class app_sub_modules
    {
        public app_sub_modules()
        {
            this.app_module_operations = new HashSet<app_module_operations>();
        }
    
        public int id { get; set; }
        public int mid { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<bool> isempty { get; set; }
        public int app_base_module_id { get; set; }
        public string name { get; set; }
    
        public virtual app_base_modules app_base_modules { get; set; }
        public virtual ICollection<app_module_operations> app_module_operations { get; set; }
    }
}
