//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gumruk.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class app_module_operations
    {
        public int id { get; set; }
        public int d_b_tables_id { get; set; }
        public string operation { get; set; }
        public string query { get; set; }
        public int app_sub_module_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string Explanation { get; set; }
    
        public virtual app_sub_modules app_sub_modules { get; set; }
        public virtual d_b_tables d_b_tables { get; set; }
    }
}
