//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gumruk.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_b_column_types
    {
        public d_b_column_types()
        {
            this.d_b_columns = new HashSet<d_b_columns>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public int mid { get; set; }
        public Nullable<bool> isempty { get; set; }
    
        public virtual ICollection<d_b_columns> d_b_columns { get; set; }
    }
}
