//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gumruk.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_b_tables
    {
        public d_b_tables()
        {
            this.d_b_columns = new HashSet<d_b_columns>();
            this.d_b_table_explanation = new HashSet<d_b_table_explanation>();
            this.app_module_operations = new HashSet<app_module_operations>();
            this.ModulesTables = new HashSet<ModulesTables>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string details { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public int d_b_schemasId { get; set; }
        public int mid { get; set; }
        public Nullable<bool> isempty { get; set; }
        public Nullable<bool> isView { get; set; }
    
        public virtual d_b_schemas d_b_schemas { get; set; }
        public virtual ICollection<d_b_columns> d_b_columns { get; set; }
        public virtual ICollection<d_b_table_explanation> d_b_table_explanation { get; set; }
        public virtual ICollection<app_module_operations> app_module_operations { get; set; }
        public virtual ICollection<ModulesTables> ModulesTables { get; set; }
    }
}
