//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gumruk.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_b_table_explanation
    {
        public int id { get; set; }
        public int mid { get; set; }
        public int db_table_id { get; set; }
        public string details { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<bool> isempty { get; set; }
        public Nullable<int> userId { get; set; }
    
        public virtual users users { get; set; }
        public virtual d_b_tables d_b_tables { get; set; }
    }
}
