//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gumruk.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERxml
    {
        public int id { get; set; }
        public Nullable<int> schemaid { get; set; }
        public string tablesid { get; set; }
        public string xmlData { get; set; }
        public string ErName { get; set; }
    }
}
