//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gumruk.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Limanlar
    {
        public int ID { get; set; }
        public Nullable<int> UlkeID { get; set; }
        public string LimanAdi { get; set; }
        public string LimanKodu { get; set; }
    }
}
