//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gumruk.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class migrations
    {
        public int id { get; set; }
        public string migration { get; set; }
        public int batch { get; set; }
        public int mid { get; set; }
        public Nullable<bool> isempty { get; set; }
    }
}
