//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gumruk.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modules
    {
        public Modules()
        {
            this.SubModules = new HashSet<SubModules>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<bool> isempty { get; set; }
        public Nullable<int> modType { get; set; }
    
        public virtual ICollection<SubModules> SubModules { get; set; }
        public virtual Modules Modules1 { get; set; }
        public virtual Modules Modules2 { get; set; }
    }
}
