//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gumruk.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModulesTables
    {
        public int ID { get; set; }
        public Nullable<int> d_b_tablesID { get; set; }
        public Nullable<int> subModuleID { get; set; }
        public Nullable<int> moduleID { get; set; }
        public Nullable<int> fileID { get; set; }
        public Nullable<int> lineNumber { get; set; }
    
        public virtual d_b_tables d_b_tables { get; set; }
        public virtual ModulesFiles ModulesFiles { get; set; }
    }
}
