//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gumruk.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModulesFiles
    {
        public ModulesFiles()
        {
            this.SQLProcedureModules = new HashSet<SQLProcedureModules>();
            this.ModulesTables = new HashSet<ModulesTables>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Body { get; set; }
        public Nullable<int> SubModuleID { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public string formattedBody { get; set; }
        public Nullable<int> LineCount { get; set; }
    
        public virtual SubModules SubModules { get; set; }
        public virtual ICollection<SQLProcedureModules> SQLProcedureModules { get; set; }
        public virtual ICollection<ModulesTables> ModulesTables { get; set; }
    }
}
