//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gumruk.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OzelTuzelSahis
    {
        public int ID { get; set; }
        public Nullable<int> KimlikTurID { get; set; }
        public string KimlikNo { get; set; }
        public string VergiDairesiKodu { get; set; }
        public string AdiUnvani { get; set; }
        public string CaddeSokak { get; set; }
        public string İlIlce { get; set; }
        public Nullable<int> PostaKodu { get; set; }
        public Nullable<int> UlkeID { get; set; }
        public string Telefon { get; set; }
        public string Faks { get; set; }
    }
}
