//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gumruk.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SQLProcedures
    {
        public SQLProcedures()
        {
            this.SQLProcedureModules = new HashSet<SQLProcedureModules>();
        }
    
        public int ID { get; set; }
        public string body { get; set; }
        public string formattedBody { get; set; }
        public string name { get; set; }
        public Nullable<int> mid { get; set; }
        public Nullable<bool> isFormatted { get; set; }
        public Nullable<int> schema_id { get; set; }
        public string sqlText { get; set; }
        public Nullable<int> LineCount { get; set; }
        public Nullable<int> CharCount { get; set; }
        public Nullable<int> IfCount { get; set; }
    
        public virtual ICollection<SQLProcedureModules> SQLProcedureModules { get; set; }
        public virtual d_b_schemas d_b_schemas { get; set; }
    }
}
