//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gumruk.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SQLProcedureModules
    {
        public int ID { get; set; }
        public Nullable<int> SQLProcedureID { get; set; }
        public int ModuleID { get; set; }
        public int SubModuleID { get; set; }
        public Nullable<int> FileID { get; set; }
        public Nullable<int> lineNumber { get; set; }
    
        public virtual SQLProcedures SQLProcedures { get; set; }
        public virtual SubModules SubModules { get; set; }
        public virtual ModulesFiles ModulesFiles { get; set; }
    }
}
