//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gumruk.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubModules
    {
        public SubModules()
        {
            this.ModulesFiles = new HashSet<ModulesFiles>();
            this.SQLProcedureModules = new HashSet<SQLProcedureModules>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<bool> isempty { get; set; }
    
        public virtual Modules Modules { get; set; }
        public virtual ICollection<ModulesFiles> ModulesFiles { get; set; }
        public virtual ICollection<SQLProcedureModules> SQLProcedureModules { get; set; }
        public virtual SubModules SubModules1 { get; set; }
        public virtual SubModules SubModules2 { get; set; }
    }
}
