//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gumruk.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TasitBilgileri
    {
        public int ID { get; set; }
        public string Ad { get; set; }
        public string Numarasi { get; set; }
        public string ReferansNumarasi { get; set; }
        public Nullable<int> UlkeID { get; set; }
        public Nullable<int> DorseNo1 { get; set; }
        public Nullable<int> Uyruk { get; set; }
        public Nullable<int> DorseNo2 { get; set; }
        public Nullable<int> Uyruk2 { get; set; }
        public Nullable<System.DateTime> VarisTarihiVeSaati { get; set; }
    }
}
