//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gumruk.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public users()
        {
            this.d_b_table_explanation = new HashSet<d_b_table_explanation>();
            this.d_b_column_explanations = new HashSet<d_b_column_explanations>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string remember_token { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<bool> isempty { get; set; }
    
        public virtual ICollection<d_b_table_explanation> d_b_table_explanation { get; set; }
        public virtual ICollection<d_b_column_explanations> d_b_column_explanations { get; set; }
    }
}
